### ISSUE TITLE
Wrong MultiSignature Address Generation

### ISSUE THREAD

**Issue by shayanb** [vbuterin/pybitcointools#71]
This generates the wrong address for multisigniture addresses:

```
 TestMultisig = mk_multisig_script(["0254236f7d1124fc07600ad3eec5ac47393bf963fbf0608bcce255e685580d16d9","03560cad89031c412ad8619398bd43b3d673cb5bdcdac1afc46449382c6a8e0b2b"],2)

    multisig_address = p2sh_scriptaddr(TestMultisig)
```

This will Generate : __3Qu1wLEVDda4EjCCgtirUuz5kq6geoaDQW__

Although if you check with either _pycoin_ or _http://ms-brainwallet.org_, it should generate: __33byJBaS5N45RHFcatTSt9ZjiGb6nK4iV3__

**Comment by kewllife** [comment]
I had the same problem with `mk_multisig_script`. It appears there is a problem when encoding the `OP_CHECKMULTISIG` value of `174` at the end of the script. Instead of adding `AE`, its adding `5B3137345D`, which is the hex value for `[174]`. I had to just hard-code the hex value *as a string*, then it works fine.

**FROM**
    
    return serialize_script([k]+pubs+[len(pubs), 174])

**TO**

    return serialize_script([k]+pubs+[len(pubs)]) + 'ae'

I'm sure there is a much cleaner way, which is why I won't do a pull request (still studying the codebase).

**Comment by badluckiskillingme** [comment]
This issue was really nasty. And it turns out that I'm victim of it. Is there any chance to transfer from multisig 2-3 address based on such a broken script?

**Comment by shayanb** [comment]
@badluckiskillingme I don't think you can cause basically you have one address that you don't hold the required private keys for that address.
p.s. realistic username here ;)

**Comment by badluckiskillingme** [comment]
Buterin, you ***** I will remember this :> I lost ... a new car
